from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="rideshare-home"),
    path('home', views.home, name="rideshare-home"),
    path('login', views.login, name="rideshare-login"),
    path('signup', views.signup, name="rideshare-signup"),
    path('logout', views.logout, name="rideshare-logout"),
    path('rideowner', views.rideowner, name="rideshare-rideowner"),
    path('driversearchride',
         views.driversearchride, name="rideshare-driversearchride"),
    path('ridedriver', views.ridedriver, name="rideshare-ridedriver"),
    path('ridesharer', views.ridesharer, name="rideshare-ridesharer"),
    path('createride', views.createride, name="rideshare-createride"),
    path('editride/<rideid>', views.editride, name="editride"),
    path('cancel/<rideid>', views.cancelride, name="cancelride"),
    path('deleteride/<rideid>', views.deleteride, name="deleteride"),
    path('success', views.success, name="rideshare-success"),
    path('profile', views.profile, name="rideshare-profile"),
    path('editDriver', views.editDriver, name="rideshare-editDriver"),
    path('confirm/<id>',
         views.confirm, name="rideshare-confirm"),
    path('registerdriver', views.registerdriver, name="registerdriver"),
    path('searchridesharer', views.searchridesharer, name="search-sharer"),
    path('joinride/<rideid>', views.joinride, name="rideshare-join"),
    path('arrived/<rideid>', views.ridearrvied, name="ridearrvied"),
    path('cancelridesharer/<rideid>',
         views.cancelridesharer, name="cancelridesharer"),
]
