# Generated by Django 4.1.5 on 2023-02-06 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('vtype', models.CharField(max_length=20)),
                ('plateNumber', models.CharField(max_length=10)),
                ('numberOfPassagers', models.IntegerField()),
                ('specialInfo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShareRide',
            fields=[
                ('rideid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('nop', models.IntegerField()),
                ('creator', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('driverStatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('arrivalTime', models.DateTimeField()),
                ('numberOfPassagers', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('share', models.BooleanField()),
                ('shareNum', models.IntegerField()),
                ('driver', models.CharField(max_length=20)),
                ('creator', models.CharField(max_length=20)),
                ('sepReq', models.CharField(max_length=100)),
                ('leftnop', models.IntegerField()),
                ('sharer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rideshareapp.userinfo')),
            ],
        ),
    ]
