# Generated by Django 4.1.5 on 2023-02-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshareapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='sharer',
        ),
        migrations.AddField(
            model_name='ride',
            name='sharer',
            field=models.ManyToManyField(blank=True, to='rideshareapp.userinfo'),
        ),
    ]
